## Netlify Konfiguration für SPA‑Routing und Build‑Output
[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_BUILD_DEBUG = "true"
  NPM_FLAGS = "--no-audit --no-fund"
  VITE_API_URL = "https://der-automat.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://www.der-automat.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200