## Netlify Konfiguration für SPA‑Routing und Build‑Output
[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_BUILD_DEBUG = "true"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200