services:
  - type: web
    name: vfx-supervision-api
    env: node
    plan: free
    region: frankfurt
    rootDir: .
    buildCommand: npm ci
    startCommand: node server/index.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        sync: false
      - key: DISABLE_REGISTRATION
        value: "false"
      - key: OPEN_LOGIN_MODE
        value: "true"