import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

// Centralized translations for all supported languages
const translations = {
  de: {
    nav: {
      dashboard: "Dashboard",
      shots: "Shot Liste",
      settings: "Einstellungen",
      camera: "Kamera Presets",
      notes: "Notizen",
      tools: "Tools",
      sensorPreview: "Sensor Vorschau",
      sensorDb: "Sensor DB",
      fovCalculator: "FOV‑Rechner",
      lensMapper: "Lens‑Mapper",
      flickerControll: "Flicker Control",
      lightingTools: "Lighting‑Tools",
      lensEditor: "Objektiv‑Editor",
      cameraSensorEditor: "Kamera/Sensor‑Editor",
      quickstart: "Quickstart",
      feedback: "Feedback",
      login: "Login",
      users: "Nutzer",
      teams: "Teams",
      cameraControl: "Camera Control (Beta)",
    },
    feedback: {
      title: "Feedback",
      description:
        "Schicke uns dein Beta‑Feedback. Du kannst per E‑Mail oder über das Formular senden.",
      nameLabel: "Name",
      namePlaceholder: "z. B. Martin",
      emailLabel: "E‑Mail",
      emailPlaceholder: "optional",
      subjectLabel: "Betreff",
      messageLabel: "Nachricht",
      messagePlaceholder:
        "Beschreibe Problem, Gerät/Browser, Schritte zum Reproduzieren…",
      deviceLabel: "Gerät/Browser (optional)",
      devicePlaceholder: "z. B. iPadOS 17, Safari",
      pwaInstalledLabel: "PWA installiert?",
      submitEmail: "Per E‑Mail senden",
      submitForm: "Formular einreichen",
      success: "Danke! Feedback erfolgreich gesendet.",
      error: "Fehler beim Senden. Bitte per E‑Mail versuchen.",
      betaWarning:
        "Hinweis: Dies ist eine öffentlich zugängliche Demo. Bitte keine sensiblen Daten senden.",
      emailFallback:
        "Falls das Formular nicht funktioniert, nutze bitte den E‑Mail‑Button.",
    },
    settings: {
      title: "Einstellungen",
      appearance: "Darstellung",
      language: "Sprache",
      languageOptions: {
        de: "Deutsch",
        en: "Englisch",
        fr: "Französisch",
        es: "Spanisch",
      },
      offline: "Offline-Verfügbarkeit",
      offlineDescription:
        "Speichere alle Projektdaten, Shots und Bilder lokal auf dem Gerät, damit die App auch ohne Internet funktioniert.",
      offlineSaving: "Speichere…",
      offlineSaveNow: "Alle Daten auf Gerät speichern",
      offlineSavedPrefix: "Gespeichert:",
      timestampPrefix: "Stand:",
      cloudSync: {
        title: "Cloud-Synchronisierung",
        description:
          "Synchronisiere einen Daten-Snapshot zu deinem Cloudspeicher.",
        providerLabel: "Provider:",
        options: {
          genericHttp: "Generischer HTTP Upload",
        },
        labels: {
          accessToken: "Access Token:",
          filePath: "Dateipfad:",
          presignedUrl: "Presigned URL (PUT):",
          signedUrl: "Signed URL (PUT):",
          sasUrl: "SAS URL (PUT):",
          baseUrl: "Base URL:",
          username: "Benutzername:",
          passwordToken: "Passwort / App Token:",
          oauthAccessToken: "OAuth Access Token:",
          folderIdOptional: "Ordner-ID (optional):",
          targetPath: "Zielpfad:",
          uploadUrl: "Upload URL:",
          method: "Methode:",
          headersJson: "Zusätzliche Header (JSON):",
        },
        syncing: "Synchronisiere…",
        syncNow: "Jetzt synchronisieren",
        downloadNow: "Jetzt aus Cloud laden",
        completedPrefix: "Cloud Sync abgeschlossen:",
        autoSync: "Automatische Cloud-Synchronisierung",
        intervalMinutes: "Intervall (Minuten):",
        autoSyncSavedPrefix: "Cloud-Auto-Sync gespeichert:",
      },
      versioning: {
        title: "Versionierung & Backup",
        description:
          "Erstelle, lade herunter, importiere und stelle Daten-Snapshots wieder her.",
        autoBackup: "Automatisches Backup bei Änderungen",
        dailySnapshot: "Täglicher Snapshot",
        lastDailyBackupPrefix: "Letztes tägliches Backup:",
        noneYet: "Noch keines",
        creating: "Erstelle…",
        createBackupNow: "Backup jetzt erstellen",
        downloadBackupJson: "Backup herunterladen (JSON)",
        importBackup: "Backup importieren",
        savedVersionsTitle: "Gespeicherte Versionen",
        noVersions: "Keine Versionen vorhanden.",
        restoredPrefix: "Wiederhergestellt:",
        projectsLabel: "Projekte",
        shotsLabel: "Shots",
      },
    },
    common: {
      loading: "Laden...",
      save: "Speichern",
      cancel: "Abbrechen",
      back: "Zurück",
      yes: "Ja",
      no: "Nein",
      and: "und",
      notAvailable: "Nicht angegeben",
      manual: "Manuell",
      auto: "Auto",
      select: "Auswählen...",
      description: "Beschreibung",
      notes: "Notizen",
      of: "von",
      on: "An",
      off: "Aus",
      expand: "Erweitern",
      collapse: "Minimieren",
      undo: "Rückgängig",
      redo: "Wiederholen",
      saveFailedTryAgain: "Speichern fehlgeschlagen. Bitte erneut versuchen.",
    },
    action: {
      view: "Anzeigen",
      edit: "Bearbeiten",
      delete: "Löschen",
      restore: "Wiederherstellen",
      create: "Erstellen",
      add: "Hinzufügen",
      shotDetails: "Shot Details",
      open: "Öffnen",
      addSetup: "Setup hinzufügen",
      exportProjectPDF: "Projekt als PDF exportieren",
      newShot: "Neuer Shot",
    },
    shot: {
      listTitle: "Shot Liste",
      setupCount: "Kamera-Setups",
      detailsTitle: "Shot-Informationen",
      singular: "Shot",
      plural: "Shots",
      notes: "Notizen",
      newNote: "Neue Notiz",
      emptyTitle: "Keine Shots gefunden",
      emptyMessage: "Ändere die Suche oder erstelle einen neuen Shot.",
    },
    notes: {
      titleLabel: "Titel",
      contentLabel: "Inhalt",
      tagsLabel: "Tags (durch Komma getrennt):",
      filterByTags: "Nach Tags filtern:",
      addNote: "Notiz hinzufügen",
      titlePlaceholder: "Titel der Notiz",
      contentPlaceholder: "Inhalt der Notiz",
      tagsPlaceholder: "z.B. Meeting, Greenscreen, SH_001",
      canvas: {
        createSketch: "Skizze erstellen",
        tool: "Werkzeug",
        toolOptions: {
          pen: "Stift",
          rect: "Rechteck",
          arrow: "Pfeil",
          text: "Text",
        },
        text: "Text",
        textPlaceholder: "Text eingeben",
        textPrompt: "Text eingeben",
        color: "Farbe",
        brush: "Pinsel",
        loadBackground: "Hintergrund laden",
        clear: "Leeren",
        savePng: "Als PNG speichern",
        exportJson: "Als JSON exportieren",
        importJson: "JSON importieren",
        applyToNote: "In Notiz übernehmen",
        filePrefix: "skizze",
        jsonImportError: "Fehler beim Import der JSON:",
      },
    },
    auth: {
      loginTitle: "Login",
      currentUser: "Angemeldet als",
      notLoggedIn: "Nicht angemeldet",
      enterNameLabel: "Name eingeben",
      enterNamePlaceholder: "z.B. Max Mustermann",
      loginButton: "Einloggen",
      logoutButton: "Abmelden",
      existingUsers: "Vorhandene Nutzer",
      noUsersYet: "Noch keine Nutzer angelegt",
      publicDataWarning:
        "Hinweis: Dies ist eine öffentlich zugängliche Demo. Bitte keine wichtigen oder geschützten Projektdaten hochladen.",
    },
    users: {
      title: "Benutzerverzeichnis",
      description: "Lege Nutzer an, die Shots erstellen können.",
      nameLabel: "Name",
      namePlaceholder: "z.B. Max Mustermann",
      addUserButton: "Nutzer hinzufügen",
      listTitle: "Nutzer",
      empty: "Noch keine Nutzer",
      userId: "ID",
      delete: "Löschen",
    },
    user: {
      createdBy: "Erstellt von",
    },
    teams: {
      title: "Teams",
      description: "Lege Teams an und verwalte Mitglieder für Projekte.",
      nameLabel: "Teamname",
      namePlaceholder: "z.B. Kameraunit A",
      addTeamButton: "Team hinzufügen",
      listTitle: "Teams",
      empty: "Noch keine Teams",
      delete: "Löschen",
      members: "Mitglieder",
      noMembers: "Keine Mitglieder",
      removeMember: "Entfernen",
      addMemberPlaceholder: "Mitglied hinzufügen…",
    },
    search: {
      shotsPlaceholder: "Suche nach Shot-Name oder Beschreibung...",
      notesPlaceholder: "Suche in Notizen...",
    },
    status: {
      all: "Alle",
      completed: "Abgeschlossen",
      inProgress: "In Bearbeitung",
      pending: "Ausstehend",
    },
    section: {
      cameraSetup: "Kamera Setup",
      cameraSettings: "Kamera-Einstellungen",
      lensSettings: "Objektiv-Einstellungen",
      cameraMovement: "Kamera-Bewegung",
      vfxTasks: "VFX Aufgaben",
      references: "Referenzen",
      setupLabel: "Setup",
    },
    camera: {
      manufacturer: "Hersteller",
      model: "Kamera",
      sensor: "Sensor",
      iso: "ISO",
      framerate: "Framerate",
      shutter: "Verschlusszeit",
      shutterAngle: "Shutter Angle",
      wb: "Weißabgleich",
      format: "Format",
      codec: "Codec",
      colorSpace: "Farbraum",
      lut: "Viewer LUT",
      imageStabilization: "Bildstabilisierung",
      ndFilter: "Interner ND-Filter",
      selectManufacturer: "Hersteller auswählen...",
      selectModel: "Modell auswählen...",
      selectCodec: "Codec auswählen...",
      selectColorSpace: "Farbraum auswählen...",
      selectLut: "Viewer LUT auswählen...",
      selectFormat: "Format auswählen...",
      manualISOPlaceholder: "Eigenen ISO-Wert eingeben, z.B. 850",
      manualWBPlaceholder: "z.B. 4200K oder Kelvin-Wert eingeben",
      wbOptions: {
        daylight5600: "Tageslicht (5600K)",
        tungsten3200: "Kunstlicht (3200K)",
        fluorescent: "Leuchtstoff",
        cloudy: "Bewölkt",
        shade: "Schatten",
      },
      imageStabilizationOptions: {
        off: "Aus",
        standard: "Standard",
        active: "Aktiv",
        boost: "Boost",
      },
      ndFilterOptions: {
        none: "Kein",
        nd03_1Stop: "ND 0.3 (1 Stop)",
        nd06_2Stops: "ND 0.6 (2 Stops)",
        nd09_3Stops: "ND 0.9 (3 Stops)",
        nd12_4Stops: "ND 1.2 (4 Stops)",
        nd15_5Stops: "ND 1.5 (5 Stops)",
        nd18_6Stops: "ND 1.8 (6 Stops)",
      },
    },
    lens: {
      manufacturer: "Objektiv-Hersteller",
      lens: "Objektiv",
      focalLength: "Brennweite",
      aperture: "Blende",
      focus: "Fokus",
      focusDistance: "Fokus-Distanz",
      hyperfocalDistance: "Hyperfokale Distanz",
      lensStabilization: "Objektiv-Bildstabilisierung",
      range: "Bereich",
      enterValueBetween: "Bitte Wert zwischen",
      filter: "Filter",
      addFilter: "Filter hinzufügen",
      anamorphic: "Anamorphe Linse",
      selectManufacturer: "Hersteller auswählen...",
      focalLengthZoom: "Brennweite bei Zoom Optik",
      hyperfocalPlaceholder: "z.B. 5.2 m",
      aperturePlaceholder: "z.B. f/2.8",
      focusDistancePlaceholder: "z.B. 3 m",
    },
    movement: {
      movement: "Bewegung",
      type: "Bewegungsart",
      direction: "Richtung",
      path: "Pfad",
      speed: "Geschwindigkeit",
      cameraHeight: "Kamera-Höhe",
      dollySetup: "Dolly Setup",
      trackType: "Track-Typ (Dolly)",
      trackTypeStraight: "Gerade",
      trackTypeCurve: "Kurve",
      trackLength: "Track-Länge",
      head: "Head",
      headFluid: "Fluid",
      headGearhead: "Gearhead",
      mount: "Montage",
      sliderLength: "Slider-Länge",
      sliderOrientation: "Slider-Ausrichtung",
      orientationHorizontal: "Horizontal",
      orientationVertical: "Vertikal",
      orientationDiagonal: "Diagonal",
      directionOptions: {
        forward: "Vorwärts",
        backward: "Rückwärts",
        sideways: "Seitwärts",
        circle: "Kreis",
        up: "Hoch",
        down: "Runter",
        diagonal: "Diagonal",
      },
      typeOptions: {
        dolly: "Dolly",
        slider: "Slider",
        craneJib: "Kran/Jib",
        gimbal: "Gimbal",
        steadicam: "Steadicam",
        handheld: "Handheld",
        tripodStatic: "Stativ (Static)",
      },
      jibArmLength: "Kran/Jib-Armlänge",
      mountCraneJib: "Montage (Kran/Jib)",
      panDegrees: "Pan (°)",
      tiltDegrees: "Tilt (°)",
      armLengthPlaceholder: "z.B. 3 m",
      speedPlaceholder: "z.B. langsam oder 0.8 m/s",
      cameraHeightPlaceholder: "z.B. 1.60 m",
      trackLengthPlaceholder: "z.B. 10 m",
      sliderLengthPlaceholder: "z.B. 1.0 m",
      mountingPlaceholder: "z.B. Dolly, Stativ, Bodenplatte",
      mountPlaceholder: "z.B. Low-Mode, Hi-Hat",
      panPlaceholder: "z.B. 30°",
      tiltPlaceholder: "z.B. 10°",
      notesPlaceholder: "Zusätzliche Hinweise zur Bewegung/Setup",
    },
    vfx: {
      supervisor: "VFX Supervisor",
      tasks: "Aufgaben",
      plates: "Plates",
      checklist: {
        cleanplates: "Cleanplates gefilmt",
        hdris: "HDRIs aufgenommen",
        setReferences: "Set-Referenzen fotografiert",
        chromeBall: "Chrome Ball verwendet",
        grayBall: "Gray Ball verwendet",
        colorChecker: "ColorChecker verwendet",
        distortionGrids: "Distortion Grids gefilmt",
        measurementsTaken: "Maße genommen",
        threeDScans: "3D Scans erstellt",
      },
      distortionNotesPlaceholder: "Zusätzliche Hinweise",
      measurementsNotesPlaceholder: "Zusätzliche Messhinweise",
      threeDScansNotesPlaceholder: "Scandetails, Kalibrierung, etc.",
    },
    dashboard: {
      title: "Dashboard",
      myProjects: "Meine Projekte",
      viewShots: "Shots anzeigen",
      newProject: "Neues Projekt erstellen",
      plannedShotsCount: "Anzahl geplanter Shots",
      production: "Produktion",
      director: "Regisseur",
      cinematographer: "Kameramann/frau",
      vfxSupervisor: "VFX Supervisor",
      teamLabel: "Team",
      selectTeam: "Team auswählen…",
      noTeam: "Kein Team",
      created: "Erstellt",
      progress: "Fortschritt",
      projectName: "Projektname",
      projectNamePlaceholder: "Projektname eingeben",
      productionPlaceholder: "Name der Produktionsfirma",
      directorPlaceholder: "Name des Regisseurs",
      cinematographerPlaceholder: "Name des Kameramanns/der Kamerafrau",
      vfxSupervisorPlaceholder: "Name des VFX Supervisors",
      createProject: "Projekt erstellen",
      projectDetails: "Projekt Details",
      emptyTitle: "Noch keine Projekte",
      emptyMessage: "Erstelle dein erstes Projekt, um loszulegen.",
    },
    quickstart: {
      title: "Quickstart",
      intro:
        "In wenigen Schritten startklar: Login, Nutzer/Teams, Projekte und Shots.",
      sections: {
        loginTitle: "1) Login",
        loginText:
          "Gehe zu Login, gib einen Namen ein (z. B. „Martin“ — Admin). Du kannst auch aus vorhandenen Nutzern wählen.",
        usersTeamsTitle: "2) Nutzer & Teams",
        usersTeamsText:
          "Lege Nutzer an (Users) und erstelle Teams (Teams). Füge Mitglieder zu Teams hinzu, um Projekte zuzuordnen.",
        projectTitle: "3) Projekt anlegen",
        projectText:
          "Im Dashboard neues Projekt erstellen: Name, Produktion, Regie, DOP, VFX Supervisor. Team auswählen und geplante Shots angeben.",
        shotsTitle: "4) Shots verwalten",
        shotsText:
          "Öffne die Shot Liste, suche und bearbeite Shots. Plane Kamera-Setups, trage Status und Notizen ein.",
        notesTitle: "5) Notizen",
        notesText:
          "Erstelle und tagge Notizen, um Set-Infos und Todo-Punkte festzuhalten.",
        cameraToolsTitle: "6) Kamera & Tools",
        cameraToolsText:
          "Verwalte Kamera-Presets und nutze Tools wie Sensor Vorschau, FOV‑Rechner, Lens‑Mapper, Flicker Controll und Lighting‑Tools.",
        backupTitle: "7) Backup & Sync",
        backupText:
          "Sichere Daten lokal (Offline‑Verfügbarkeit) und nutze Versionierung & Backup. Optional: Cloud‑Synchronisierung unter Einstellungen → Cloud‑Synchronisierung.",
      },
      ctaLogin: "Zum Login",
      ctaUsers: "Users öffnen",
      ctaTeams: "Teams öffnen",
      ctaDashboard: "Zum Dashboard",
      ctaShots: "Shot Liste öffnen",
      ctaNotes: "Notes öffnen",
      ctaStart: "Jetzt starten",
    },
    tools: {
      flicker: {
        title: "Flicker Control",
        cameraInfo: "Kamera‑Infos",
        mainsFrequency: "Netzfrequenz",
        framerate: "Framerate",
        flickerSafe: "Flicker‑safe",
        shutterAngle: "Shutter",
        exposureTime: "Belichtungszeit",
        na: "N/A",
        manufacturer: "Kamera Hersteller",
        arriLogC3: "ARRI LogC3",
        arriLogC4: "ARRI LogC4",
        eiBehavior: "EI Verhalten",
        shutterCalcTitle: "Shutter‑Angle Rechner",
        framerateFpsLabel: "Framerate (fps)",
        shutterAngleLabel: "Shutter Angle (°)",
        exposureTimeLabel: "Belichtungszeit",
        apply180Rule: "180°‑Regel anwenden",
        formulaLabel: "Formel: t = (Angle/360) · (1/FPS)",
      },
      fov: {
        header: "FOV‑Rechner",
        description:
          "Berechne Sichtfeld basierend auf Sensorformat und Brennweite.",
        infoTitle: "Info",
        legendColorsTitle: "Diagrammfarben",
        legendBlue:
          "Blau: Vertikaler FOV (VFOV) – obere/untere Extremstrahlen; blauer Punkt = optische Mitte.",
        legendRed:
          "Rot: Horizontaler FOV (HFOV) – linke/rechte Extremstrahlen.",
        legendGray:
          "Grau: Sensorrahmen (rechts) in mm, inkl. gestrichelte Diagonale (DFOV).",
        readTitle: "Was du ablesen kannst",
        readHFOV: "HFOV/VFOV/DFOV: Winkelwerte aktualisieren sich live.",
        readSensor: "Sensorgröße: Breite × Höhe in mm passend zum Format.",
        readCrop: "Crop‑Faktor: Verhältnis der Sensor‑Diagonal zu Vollformat.",
        hintTitle: "Hinweis",
        hintText:
          "Schematische Darstellung. Zeigt Winkelbeziehungen und Sensormaßstab, keine Projektion/Verzeichnung.",
        controls: {
          manufacturer: "Hersteller",
          camera: "Kamera",
          format: "Format",
          selectPrompt: "Bitte wählen…",
          lensManufacturer: "Objektiv‑Hersteller",
          lens: "Objektiv",
          anamorph: "Anamorph",
          focalLengthMm: "Brennweite (mm)",
          projection: "Projektion",
          projectionOptions: {
            rectilinear: "Rectilinear",
            fisheyeEquidistant: "Fisheye (equidistant)",
            fisheyeStereographic: "Fisheye (stereographic)",
          },
          apertureFN: "Blende (f/N)",
          focusDistanceM: "Fokus‑Distanz (m)",
          focusDistance: "Fokus‑Distanz",
          resultTitle: "Ergebnis",
          sensorSize: "Sensorgröße",
          lensInfo: "Objektiv",
          lensType: "Objektiv‑Typ",
          anamorphFactor: "Anamorph‑Faktor",
          horizontal: "Horizontal",
          vertical: "Vertikal",
          diagonal: "Diagonal",
          cropVsFF: "Crop‑Faktor (vs. Vollformat)",
          notAvailable: "Nicht verfügbar",
          diagramTitle: "FOV Diagramm",
          panel2D: "2D",
          panel3D: "3D",
        },
        threeD: {
          view3D: "3D Ansicht:",
          projectionIsometric: "Isometrisch",
          projectionPerspective: "Perspektivisch",
          zoom: "Zoom",
          reset: "Reset",
          selectSensorFocalToSee3D:
            "Bitte Sensor & Brennweite auswählen, um die 3D‑Ansicht zu sehen.",
          sensorPosition: "Sensor‑Position",
          legendFocus: "Fokus",
          legendNear: "Nahgrenze",
          legendFar: "Ferngrenze",
          labelHFOV: "HFOV",
          labelVFOV: "VFOV",
          labelSensor: "Sensor",
        },
      },
    },
  },

  en: {
    nav: {
      dashboard: "Dashboard",
      shots: "Shot List",
      settings: "Settings",
      camera: "Camera Presets",
      notes: "Notes",
      tools: "Tools",
      sensorPreview: "Sensor Preview",
      sensorDb: "Sensor DB",
      fovCalculator: "FOV Calculator",
      lensMapper: "Lens Mapper",
      flickerControll: "Flicker Control",
      lightingTools: "Lighting Tools",
      lensEditor: "Lens Editor",
      cameraSensorEditor: "Camera/Sensor Editor",
      quickstart: "Quickstart",
      feedback: "Feedback",
      login: "Login",
      users: "Users",
      teams: "Teams",
      cameraControl: "Camera Control (Beta)",
    },
    feedback: {
      title: "Feedback",
      description:
        "Send us your beta feedback. You can use email or submit the form.",
      nameLabel: "Name",
      namePlaceholder: "e.g., Martin",
      emailLabel: "Email",
      emailPlaceholder: "optional",
      subjectLabel: "Subject",
      messageLabel: "Message",
      messagePlaceholder:
        "Describe the issue, device/browser, steps to reproduce…",
      deviceLabel: "Device/Browser (optional)",
      devicePlaceholder: "e.g., iPadOS 17, Safari",
      pwaInstalledLabel: "PWA installed?",
      submitEmail: "Send via Email",
      submitForm: "Submit form",
      success: "Thanks! Feedback submitted successfully.",
      error: "Submission failed. Please try via email.",
      betaWarning:
        "Note: This demo is public. Please do not send sensitive data.",
      emailFallback: "If the form fails, please use the email button.",
    },
    settings: {
      title: "Settings",
      appearance: "Appearance",
      language: "Language",
      languageOptions: {
        de: "German",
        en: "English",
        fr: "French",
        es: "Spanish",
      },
      offline: "Offline availability",
      offlineDescription:
        "Save all project data, shots, and images locally to enable offline use.",
      offlineSaving: "Saving…",
      offlineSaveNow: "Save all data to device",
      offlineSavedPrefix: "Saved:",
      timestampPrefix: "As of:",
      cloudSync: {
        title: "Cloud Synchronization",
        description: "Sync a data snapshot to your cloud storage.",
        providerLabel: "Provider:",
        options: {
          genericHttp: "Generic HTTP Upload",
        },
        labels: {
          accessToken: "Access Token:",
          filePath: "File path:",
          presignedUrl: "Presigned URL (PUT):",
          signedUrl: "Signed URL (PUT):",
          sasUrl: "SAS URL (PUT):",
          baseUrl: "Base URL:",
          username: "Username:",
          passwordToken: "Password / App Token:",
          oauthAccessToken: "OAuth Access Token:",
          folderIdOptional: "Folder ID (optional):",
          targetPath: "Target path:",
          uploadUrl: "Upload URL:",
          method: "Method:",
          headersJson: "Additional Headers (JSON):",
        },
        syncing: "Syncing…",
        syncNow: "Sync now",
        downloadNow: "Download from cloud",
        completedPrefix: "Cloud sync completed:",
        autoSync: "Automatic cloud synchronization",
        intervalMinutes: "Interval (minutes):",
        autoSyncSavedPrefix: "Cloud auto-sync saved:",
      },
      versioning: {
        title: "Versioning & Backup",
        description: "Create, download, import, and restore data snapshots.",
        autoBackup: "Automatic backup on changes",
        dailySnapshot: "Daily snapshot",
        lastDailyBackupPrefix: "Last daily backup:",
        noneYet: "None yet",
        creating: "Creating…",
        createBackupNow: "Create backup now",
        downloadBackupJson: "Download backup (JSON)",
        importBackup: "Import backup",
        savedVersionsTitle: "Saved Versions",
        noVersions: "No versions available.",
        restoredPrefix: "Restored:",
        projectsLabel: "Projects",
        shotsLabel: "Shots",
      },
    },
    common: {
      loading: "Loading...",
      save: "Save",
      cancel: "Cancel",
      back: "Back",
      yes: "Yes",
      no: "No",
      and: "and",
      notAvailable: "Not specified",
      manual: "Manual",
      auto: "Auto",
      select: "Select...",
      description: "Description",
      notes: "Notes",
      of: "of",
      on: "On",
      off: "Off",
      expand: "Expand",
      collapse: "Collapse",
      undo: "Undo",
      redo: "Redo",
      saveFailedTryAgain: "Save failed. Please try again.",
    },
    action: {
      view: "View",
      edit: "Edit",
      delete: "Delete",
      restore: "Restore",
      create: "Create",
      add: "Add",
      shotDetails: "Shot Details",
      open: "Open",
      addSetup: "Add setup",
      exportProjectPDF: "Export project as PDF",
      newShot: "New Shot",
    },
    shot: {
      listTitle: "Shot List",
      setupCount: "Camera Setups",
      detailsTitle: "Shot Information",
      singular: "Shot",
      plural: "Shots",
      notes: "Notes",
      newNote: "New Note",
      emptyTitle: "No shots found",
      emptyMessage: "Adjust your search or create a new shot.",
    },
    notes: {
      titleLabel: "Title",
      contentLabel: "Content",
      tagsLabel: "Tags (comma-separated):",
      filterByTags: "Filter by tags:",
      addNote: "Add Note",
      titlePlaceholder: "Note title",
      contentPlaceholder: "Note content",
      tagsPlaceholder: "e.g., Meeting, Greenscreen, SH_001",
      canvas: {
        createSketch: "Create Sketch",
        tool: "Tool",
        toolOptions: {
          pen: "Pen",
          rect: "Rectangle",
          arrow: "Arrow",
          text: "Text",
        },
        text: "Text",
        textPlaceholder: "Enter text",
        textPrompt: "Enter text",
        color: "Color",
        brush: "Brush",
        loadBackground: "Load background",
        clear: "Clear",
        savePng: "Save PNG",
        exportJson: "Export JSON",
        importJson: "Import JSON",
        applyToNote: "Apply to note",
        filePrefix: "sketch",
        jsonImportError: "Error importing JSON:",
      },
    },
    auth: {
      loginTitle: "Login",
      currentUser: "Logged in as",
      notLoggedIn: "Not logged in",
      enterNameLabel: "Enter name",
      enterNamePlaceholder: "e.g., Max Mustermann",
      loginButton: "Log in",
      logoutButton: "Log out",
      existingUsers: "Existing users",
      noUsersYet: "No users yet",
      publicDataWarning:
        "Note: This is a publicly accessible demo. Please do not upload important or protected project data.",
    },
    users: {
      title: "User Directory",
      description: "Create users who can create shots.",
      nameLabel: "Name",
      namePlaceholder: "e.g., Max Mustermann",
      addUserButton: "Add user",
      listTitle: "Users",
      empty: "No users yet",
      userId: "ID",
      delete: "Delete",
    },
    user: {
      createdBy: "Created by",
    },
    teams: {
      title: "Teams",
      description: "Create teams and manage members for projects.",
      nameLabel: "Team name",
      namePlaceholder: "e.g., Camera Unit A",
      addTeamButton: "Add team",
      listTitle: "Teams",
      empty: "No teams yet",
      delete: "Delete",
      members: "Members",
      noMembers: "No members",
      removeMember: "Remove",
      addMemberPlaceholder: "Add member…",
    },
    search: {
      shotsPlaceholder: "Search by shot name or description...",
      notesPlaceholder: "Search in notes...",
    },
    status: {
      all: "All",
      completed: "Completed",
      inProgress: "In Progress",
      pending: "Pending",
    },
    section: {
      cameraSetup: "Camera Setup",
      cameraSettings: "Camera Settings",
      lensSettings: "Lens Settings",
      cameraMovement: "Camera Movement",
      vfxTasks: "VFX Tasks",
      references: "References",
      setupLabel: "Setup",
    },
    camera: {
      manufacturer: "Manufacturer",
      model: "Camera",
      sensor: "Sensor",
      iso: "ISO",
      framerate: "Framerate",
      shutter: "Shutter Speed",
      shutterAngle: "Shutter Angle",
      wb: "White Balance",
      format: "Format",
      codec: "Codec",
      colorSpace: "Color Space",
      lut: "Viewer LUT",
      imageStabilization: "Image Stabilization",
      ndFilter: "Internal ND Filter",
      selectManufacturer: "Select manufacturer...",
      selectModel: "Select model...",
      selectCodec: "Select codec...",
      selectColorSpace: "Select color space...",
      selectLut: "Select Viewer LUT...",
      selectFormat: "Select format...",
      manualISOPlaceholder: "Enter custom ISO, e.g., 850",
      manualWBPlaceholder: "e.g., 4200K or enter Kelvin value",
      wbOptions: {
        daylight5600: "Daylight (5600K)",
        tungsten3200: "Tungsten (3200K)",
        fluorescent: "Fluorescent",
        cloudy: "Cloudy",
        shade: "Shade",
      },
      imageStabilizationOptions: {
        off: "Off",
        standard: "Standard",
        active: "Active",
        boost: "Boost",
      },
      ndFilterOptions: {
        none: "None",
        nd03_1Stop: "ND 0.3 (1 stop)",
        nd06_2Stops: "ND 0.6 (2 stops)",
        nd09_3Stops: "ND 0.9 (3 stops)",
        nd12_4Stops: "ND 1.2 (4 stops)",
        nd15_5Stops: "ND 1.5 (5 stops)",
        nd18_6Stops: "ND 1.8 (6 stops)",
      },
    },
    lens: {
      manufacturer: "Lens Manufacturer",
      lens: "Lens",
      focalLength: "Focal Length",
      aperture: "Aperture",
      focus: "Focus",
      focusDistance: "Focus Distance",
      hyperfocalDistance: "Hyperfocal Distance",
      lensStabilization: "Lens Stabilization",
      range: "Range",
      enterValueBetween: "Please enter a value between",
      filter: "Filter",
      addFilter: "Add Filter",
      anamorphic: "Anamorphic Lens",
      selectManufacturer: "Select manufacturer...",
      focalLengthZoom: "Focal length (zoom optic)",
      hyperfocalPlaceholder: "e.g., 5.2 m",
      aperturePlaceholder: "e.g., f/2.8",
      focusDistancePlaceholder: "e.g., 3 m",
    },
    movement: {
      movement: "Movement",
      type: "Movement Type",
      direction: "Direction",
      path: "Path",
      speed: "Speed",
      cameraHeight: "Camera Height",
      dollySetup: "Dolly Setup",
      trackType: "Track Type (Dolly)",
      trackTypeStraight: "Straight",
      trackTypeCurve: "Curve",
      trackLength: "Track Length",
      head: "Head",
      headFluid: "Fluid",
      headGearhead: "Gearhead",
      mount: "Mounting",
      sliderLength: "Slider Length",
      sliderOrientation: "Slider Orientation",
      orientationHorizontal: "Horizontal",
      orientationVertical: "Vertical",
      orientationDiagonal: "Diagonal",
      directionOptions: {
        forward: "Forward",
        backward: "Backward",
        sideways: "Sideways",
        circle: "Circle",
        up: "Up",
        down: "Down",
        diagonal: "Diagonal",
      },
      typeOptions: {
        dolly: "Dolly",
        slider: "Slider",
        craneJib: "Crane/Jib",
        gimbal: "Gimbal",
        steadicam: "Steadicam",
        handheld: "Handheld",
        tripodStatic: "Tripod (Static)",
      },
      jibArmLength: "Crane/Jib Arm Length",
      mountCraneJib: "Mount (Crane/Jib)",
      panDegrees: "Pan (°)",
      tiltDegrees: "Tilt (°)",
      armLengthPlaceholder: "e.g., 3 m",
      speedPlaceholder: "e.g., slow or 0.8 m/s",
      cameraHeightPlaceholder: "e.g., 1.60 m",
      trackLengthPlaceholder: "e.g., 10 m",
      sliderLengthPlaceholder: "e.g., 1.0 m",
      mountingPlaceholder: "e.g., Dolly, Tripod, Baseplate",
      mountPlaceholder: "e.g., Low-Mode, Hi-Hat",
      panPlaceholder: "e.g., 30°",
      tiltPlaceholder: "e.g., 10°",
      notesPlaceholder: "Additional movement/setup notes",
    },
    vfx: {
      supervisor: "VFX Supervisor",
      tasks: "Tasks",
      plates: "Plates",
      checklist: {
        cleanplates: "Cleanplates recorded",
        hdris: "HDRIs captured",
        setReferences: "Set references photographed",
        chromeBall: "Chrome ball used",
        grayBall: "Gray ball used",
        colorChecker: "ColorChecker used",
        distortionGrids: "Distortion grids filmed",
        measurementsTaken: "Measurements taken",
        threeDScans: "3D scans created",
      },
      distortionNotesPlaceholder: "Additional notes",
      measurementsNotesPlaceholder: "Additional measurement hints",
      threeDScansNotesPlaceholder: "Scan details, calibration, etc.",
    },
    dashboard: {
      title: "Dashboard",
      myProjects: "My Projects",
      viewShots: "View Shots",
      newProject: "Create New Project",
      plannedShotsCount: "Planned Shots Count",
      production: "Production",
      director: "Director",
      cinematographer: "DOP",
      vfxSupervisor: "VFX Supervisor",
      teamLabel: "Team",
      selectTeam: "Select team…",
      noTeam: "No team",
      created: "Created",
      progress: "Progress",
      projectName: "Project Name",
      projectNamePlaceholder: "Enter project name",
      productionPlaceholder: "Production company name",
      directorPlaceholder: "Director’s name",
      cinematographerPlaceholder: "DOP’s name",
      vfxSupervisorPlaceholder: "VFX Supervisor’s name",
      createProject: "Create Project",
      projectDetails: "Project Details",
      emptyTitle: "No projects yet",
      emptyMessage: "Create your first project to get started.",
    },
    quickstart: {
      title: "Quickstart",
      intro: "Ready in a few steps: login, users/teams, projects, shots.",
      sections: {
        loginTitle: "1) Login",
        loginText:
          "Go to Login, enter a name (e.g., “Martin” — admin). You can also choose an existing user.",
        usersTeamsTitle: "2) Users & Teams",
        usersTeamsText:
          "Create users and set up teams. Add members to teams to assign projects.",
        projectTitle: "3) Create a project",
        projectText:
          "On the Dashboard, create a new project: name, production, director, DOP, VFX supervisor. Select a team and planned shots.",
        shotsTitle: "4) Manage shots",
        shotsText:
          "Open the Shot List to search and edit shots. Plan camera setups, set status, and add notes.",
        notesTitle: "5) Notes",
        notesText: "Create and tag notes to capture set information and todos.",
        cameraToolsTitle: "6) Camera & Tools",
        cameraToolsText:
          "Manage camera presets and use tools like Sensor Preview, FOV Calculator, Lens Mapper, Flicker Control, and Lighting Tools.",
        backupTitle: "7) Backup & Sync",
        backupText:
          "Save data locally (Offline availability) and use Versioning & Backup. Optionally: Cloud Sync via Settings → Cloud Synchronization.",
      },
      ctaLogin: "Go to Login",
      ctaUsers: "Open Users",
      ctaTeams: "Open Teams",
      ctaDashboard: "Go to Dashboard",
      ctaShots: "Open Shot List",
      ctaNotes: "Open Notes",
      ctaStart: "Start now",
    },
    tools: {
      flicker: {
        title: "Flicker Control",
        cameraInfo: "Camera Info",
        mainsFrequency: "Mains Frequency",
        framerate: "Framerate",
        flickerSafe: "Flicker‑safe",
        shutterAngle: "Shutter",
        exposureTime: "Exposure Time",
        na: "N/A",
        manufacturer: "Camera Manufacturer",
        arriLogC3: "ARRI LogC3",
        arriLogC4: "ARRI LogC4",
        eiBehavior: "EI Behavior",
        shutterCalcTitle: "Shutter‑Angle Calculator",
        framerateFpsLabel: "Framerate (fps)",
        shutterAngleLabel: "Shutter Angle (°)",
        exposureTimeLabel: "Exposure Time",
        apply180Rule: "Apply 180° Rule",
        formulaLabel: "Formula: t = (Angle/360) · (1/FPS)",
      },
      fov: {
        header: "FOV Calculator",
        description:
          "Compute field of view from sensor format and focal length.",
        infoTitle: "Info",
        legendColorsTitle: "Diagram colors",
        legendBlue: "Blue: Vertical FOV (VFOV); blue dot marks optical center.",
        legendRed: "Red: Horizontal FOV (HFOV) – left/right extreme rays.",
        legendGray:
          "Gray: Sensor frame (right) in mm incl. dashed diagonal (DFOV).",
        readTitle: "What you can read",
        readHFOV: "HFOV/VFOV/DFOV: angles update live.",
        readSensor: "Sensor size: width × height in mm per format.",
        readCrop: "Crop factor: sensor diagonal vs. full frame.",
        hintTitle: "Note",
        hintText:
          "Schematic view: angles and sensor scale, not lens distortion.",
        controls: {
          manufacturer: "Manufacturer",
          camera: "Camera",
          format: "Format",
          selectPrompt: "Please select…",
          lensManufacturer: "Lens Manufacturer",
          lens: "Lens",
          anamorph: "Anamorphic",
          focalLengthMm: "Focal Length (mm)",
          projection: "Projection",
          projectionOptions: {
            rectilinear: "Rectilinear",
            fisheyeEquidistant: "Fisheye (equidistant)",
            fisheyeStereographic: "Fisheye (stereographic)",
          },
          apertureFN: "Aperture (f/N)",
          focusDistanceM: "Focus Distance (m)",
          focusDistance: "Focus Distance",
          resultTitle: "Result",
          sensorSize: "Sensor Size",
          lensInfo: "Lens",
          lensType: "Lens Type",
          anamorphFactor: "Anamorphic Factor",
          horizontal: "Horizontal",
          vertical: "Vertical",
          diagonal: "Diagonal",
          cropVsFF: "Crop factor (vs. full frame)",
          notAvailable: "Not available",
          diagramTitle: "FOV Diagram",
          panel2D: "2D",
          panel3D: "3D",
        },
        threeD: {
          view3D: "3D View:",
          projectionIsometric: "Isometric",
          projectionPerspective: "Perspective",
          zoom: "Zoom",
          reset: "Reset",
          selectSensorFocalToSee3D:
            "Select sensor & focal length to see the 3D view.",
          sensorPosition: "Sensor Position",
          legendFocus: "Focus",
          legendNear: "Near limit",
          legendFar: "Far limit",
          labelHFOV: "HFOV",
          labelVFOV: "VFOV",
          labelSensor: "Sensor",
        },
      },
    },
  },

  fr: {
    nav: {
      dashboard: "Tableau de bord",
      shots: "Liste des plans",
      settings: "Paramètres",
      camera: "Préréglages caméra",
      notes: "Notes",
      tools: "Outils",
      sensorPreview: "Aperçu capteur",
      sensorDb: "Sensor DB",
      fovCalculator: "Calculateur FOV",
      lensMapper: "Lens Mapper",
      flickerControll: "Contrôle Flicker",
      lightingTools: "Outils lumière",
      lensEditor: "Éditeur d’objectif",
      cameraSensorEditor: "Éditeur caméra/capteur",
    },
    settings: {
      title: "Paramètres",
      appearance: "Apparence",
      language: "Langue",
      languageOptions: {
        de: "Allemand",
        en: "Anglais",
        fr: "Français",
        es: "Espagnol",
      },
      offline: "Disponibilité hors ligne",
    },
    common: {
      loading: "Chargement...",
      save: "Enregistrer",
      cancel: "Annuler",
      back: "Retour",
      yes: "Oui",
      no: "Non",
      and: "et",
      notAvailable: "Non spécifié",
      manual: "Manuel",
      auto: "Auto",
      select: "Sélectionner...",
      description: "Description",
      notes: "Notes",
      of: "sur",
      on: "Activé",
      off: "Désactivé",
      expand: "Développer",
      collapse: "Réduire",
      undo: "Annuler",
      redo: "Rétablir",
    },
    action: {
      view: "Voir",
      edit: "Modifier",
      delete: "Supprimer",
      create: "Créer",
      add: "Ajouter",
      shotDetails: "Détails du plan",
      open: "Ouvrir",
      addSetup: "Ajouter un setup",
      exportProjectPDF: "Exporter le projet en PDF",
      newShot: "Nouveau plan",
    },
    shot: {
      listTitle: "Liste des plans",
      setupCount: "Configurations de caméra",
      detailsTitle: "Informations du plan",
      singular: "Plan",
      plural: "Plans",
      notes: "Notes",
      newNote: "Nouvelle note",
      emptyTitle: "Aucun plan trouvé",
      emptyMessage: "Modifiez la recherche ou créez un nouveau plan.",
    },
    notes: {
      titleLabel: "Titre",
      contentLabel: "Contenu",
      tagsLabel: "Tags (séparés par des virgules) :",
      filterByTags: "Filtrer par tags :",
      addNote: "Ajouter une note",
      titlePlaceholder: "Titre de la note",
      contentPlaceholder: "Contenu de la note",
      tagsPlaceholder: "ex. Réunion, Greenscreen, SH_001",
      canvas: {
        createSketch: "Créer une esquisse",
        tool: "Outil",
        toolOptions: {
          pen: "Crayon",
          rect: "Rectangle",
          arrow: "Flèche",
          text: "Texte",
        },
        text: "Texte",
        textPlaceholder: "Saisir du texte",
        textPrompt: "Saisir du texte",
        color: "Couleur",
        brush: "Pinceau",
        loadBackground: "Charger l’arrière‑plan",
        clear: "Effacer",
        savePng: "Enregistrer en PNG",
        exportJson: "Exporter JSON",
        importJson: "Importer JSON",
        applyToNote: "Appliquer à la note",
        filePrefix: "esquisse",
        jsonImportError: "Erreur lors de l’import du JSON :",
      },
    },
    search: {
      shotsPlaceholder: "Rechercher par nom de plan ou description...",
      notesPlaceholder: "Rechercher dans les notes...",
    },
    status: {
      all: "Tous",
      completed: "Terminé",
      inProgress: "En cours",
      pending: "En attente",
    },
    section: {
      cameraSetup: "Configuration de la caméra",
      cameraSettings: "Paramètres de la caméra",
      lensSettings: "Paramètres de l’objectif",
      cameraMovement: "Mouvement de la caméra",
      vfxTasks: "Tâches VFX",
      references: "Références",
      setupLabel: "Setup",
    },
    camera: {
      manufacturer: "Fabricant",
      model: "Caméra",
      sensor: "Capteur",
      iso: "ISO",
      framerate: "Fréquence d'images",
      shutter: "Vitesse d’obturation",
      shutterAngle: "Angle d’obturation",
      wb: "Balance des blancs",
      format: "Format",
      codec: "Codec",
      colorSpace: "Espace colorimétrique",
      lut: "Viewer LUT",
      imageStabilization: "Stabilisation d'image",
      ndFilter: "Filtre ND interne",
      selectManufacturer: "Sélectionner le fabricant...",
      selectModel: "Sélectionner le modèle...",
      selectCodec: "Sélectionner le codec...",
      selectColorSpace: "Sélectionner l’espace colorimétrique...",
      selectLut: "Sélectionner une Viewer LUT...",
      selectFormat: "Sélectionner le format...",
      manualISOPlaceholder: "Saisir ISO personnalisé, p. ex. 850",
      manualWBPlaceholder: "p. ex., 4200K ou entrer la valeur Kelvin",
      wbOptions: {
        daylight5600: "Lumière du jour (5600K)",
        tungsten3200: "Tungstène (3200K)",
        fluorescent: "Fluorescent",
        cloudy: "Nuageux",
        shade: "Ombre",
      },
      imageStabilizationOptions: {
        off: "Désactivée",
        standard: "Standard",
        active: "Active",
        boost: "Boost",
      },
      ndFilterOptions: {
        none: "Aucun",
        nd03_1Stop: "ND 0.3 (1 stop)",
        nd06_2Stops: "ND 0.6 (2 stops)",
        nd09_3Stops: "ND 0.9 (3 stops)",
        nd12_4Stops: "ND 1.2 (4 stops)",
        nd15_5Stops: "ND 1.5 (5 stops)",
        nd18_6Stops: "ND 1.8 (6 stops)",
      },
    },
    lens: {
      manufacturer: "Fabricant de l’objectif",
      lens: "Objectif",
      focalLength: "Focale",
      aperture: "Ouverture",
      focus: "Mise au point",
      focusDistance: "Distance de mise au point",
      hyperfocalDistance: "Distance hyperfocale",
      lensStabilization: "Stabilisation de l’objectif",
      range: "Plage",
      enterValueBetween: "Veuillez saisir une valeur entre",
      filter: "Filtre",
      addFilter: "Ajouter un filtre",
      anamorphic: "Lentille anamorphique",
      selectManufacturer: "Sélectionner le fabricant...",
      focalLengthZoom: "Focale (zoom)",
      hyperfocalPlaceholder: "p. ex., 5,2 m",
      aperturePlaceholder: "p. ex., f/2,8",
      focusDistancePlaceholder: "p. ex., 3 m",
    },
    movement: {
      movement: "Mouvement",
      type: "Type de mouvement",
      direction: "Direction",
      path: "Trajectoire",
      speed: "Vitesse",
      cameraHeight: "Hauteur de la caméra",
      dollySetup: "Configuration dolly",
      trackType: "Type de rail (Dolly)",
      trackTypeStraight: "Droite",
      trackTypeCurve: "Courbe",
      trackLength: "Longueur du rail",
      head: "Tête",
      headFluid: "Fluide",
      headGearhead: "Gearhead",
      mount: "Montage",
      sliderLength: "Longueur du slider",
      sliderOrientation: "Orientation du slider",
      orientationHorizontal: "Horizontal",
      orientationVertical: "Vertical",
      orientationDiagonal: "Diagonal",
      directionOptions: {
        forward: "Avant",
        backward: "Arrière",
        sideways: "Latéral",
        circle: "Cercle",
        up: "Haut",
        down: "Bas",
        diagonal: "Diagonal",
      },
      typeOptions: {
        dolly: "Dolly",
        slider: "Slider",
        craneJib: "Grue/Jib",
        gimbal: "Gimbal",
        steadicam: "Steadicam",
        handheld: "À main levée",
        tripodStatic: "Trépied (statique)",
      },
      jibArmLength: "Longueur du bras de grue/jib",
      mountCraneJib: "Montage (grue/jib)",
      panDegrees: "Panoramique (°)",
      tiltDegrees: "Inclinaison (°)",
      armLengthPlaceholder: "p. ex., 3 m",
      speedPlaceholder: "p. ex., lent ou 0,8 m/s",
      cameraHeightPlaceholder: "p. ex., 1,60 m",
      trackLengthPlaceholder: "p. ex., 10 m",
      sliderLengthPlaceholder: "p. ex., 1,0 m",
      mountingPlaceholder: "p. ex., Dolly, Trépied, Platine",
      mountPlaceholder: "p. ex., Low-Mode, Hi-Hat",
      panPlaceholder: "p. ex., 30°",
      tiltPlaceholder: "p. ex., 10°",
      notesPlaceholder: "Notes supplémentaires sur le mouvement/le setup",
    },
    vfx: {
      supervisor: "Superviseur VFX",
      tasks: "Tâches",
      plates: "Plates",
      checklist: {
        cleanplates: "Cleanplates filmés",
        hdris: "HDRIs capturés",
        setReferences: "Références de plateau photographiées",
        chromeBall: "Chrome ball utilisée",
        grayBall: "Gray ball utilisée",
        colorChecker: "ColorChecker utilisé",
        distortionGrids: "Grilles de distorsion filmées",
        measurementsTaken: "Mesures prises",
        threeDScans: "Scans 3D réalisés",
      },
      distortionNotesPlaceholder: "Notes supplémentaires",
      measurementsNotesPlaceholder: "Indications de mesure supplémentaires",
      threeDScansNotesPlaceholder: "Détails du scan, calibration, etc.",
    },
    dashboard: {
      title: "Tableau de bord",
      myProjects: "Mes projets",
      viewShots: "Voir les plans",
      newProject: "Créer un nouveau projet",
      plannedShotsCount: "Nombre de plans prévus",
      production: "Production",
      director: "Réalisateur",
      cinematographer: "Directeur de la photographie",
      vfxSupervisor: "Superviseur VFX",
      created: "Créé",
      progress: "Progression",
      projectName: "Nom du projet",
      projectNamePlaceholder: "Saisir le nom du projet",
      productionPlaceholder: "Nom de la société de production",
      directorPlaceholder: "Nom du réalisateur",
      cinematographerPlaceholder: "Nom du directeur de la photographie",
      vfxSupervisorPlaceholder: "Nom du superviseur VFX",
      createProject: "Créer le projet",
      projectDetails: "Détails du projet",
      emptyTitle: "Pas encore de projets",
      emptyMessage: "Créez votre premier projet pour commencer.",
    },
    tools: {
      flicker: {
        title: "Contrôle Flicker",
        cameraInfo: "Infos caméra",
        mainsFrequency: "Fréquence secteur",
        framerate: "Fréquence d'images",
        flickerSafe: "Sans scintillement",
        shutterAngle: "Obturateur",
        exposureTime: "Temps d'exposition",
        na: "N/A",
        manufacturer: "Fabricant caméra",
        arriLogC3: "ARRI LogC3",
        arriLogC4: "ARRI LogC4",
        eiBehavior: "Comportement EI",
        shutterCalcTitle: "Calculateur d'angle d'obturateur",
        framerateFpsLabel: "Fréquence (fps)",
        shutterAngleLabel: "Angle d’obturateur (°)",
        exposureTimeLabel: "Temps d'exposition",
        apply180Rule: "Appliquer la règle des 180°",
        formulaLabel: "Formule : t = (Angle/360) · (1/FPS)",
      },
      fov: {
        header: "Calculateur FOV",
        description:
          "Calcule le champ de vision selon format capteur et focale.",
        infoTitle: "Info",
        legendColorsTitle: "Couleurs du diagramme",
        legendBlue: "Bleu : VFOV ; point bleu = centre optique.",
        legendRed: "Rouge : HFOV – rayons extrêmes gauche/droite.",
        legendGray:
          "Gris : cadre capteur (droite) en mm, diagonale en pointillés (DFOV).",
        readTitle: "Ce que tu peux lire",
        readHFOV: "HFOV/VFOV/DFOV : valeurs mises à jour en direct.",
        readSensor: "Taille du capteur : largeur × hauteur en mm.",
        readCrop: "Facteur de crop : diagonale capteur vs. plein format.",
        hintTitle: "Remarque",
        hintText:
          "Vue schématique : angles et échelle, pas la distorsion réelle.",
        controls: {
          manufacturer: "Fabricant",
          camera: "Caméra",
          format: "Format",
          selectPrompt: "Veuillez sélectionner…",
          lensManufacturer: "Fabricant de l’objectif",
          lens: "Objectif",
          anamorph: "Anamorphique",
          focalLengthMm: "Focale (mm)",
          projection: "Projection",
          projectionOptions: {
            rectilinear: "Rectilinéaire",
            fisheyeEquidistant: "Fisheye (équidist.)",
            fisheyeStereographic: "Fisheye (stéréogr.)",
          },
          apertureFN: "Ouverture (f/N)",
          focusDistanceM: "Distance de MAP (m)",
          focusDistance: "Distance de MAP",
          resultTitle: "Résultat",
          sensorSize: "Taille du capteur",
          lensInfo: "Objectif",
          lensType: "Type d'objectif",
          anamorphFactor: "Facteur anamorphique",
          horizontal: "Horizontal",
          vertical: "Vertical",
          diagonal: "Diagonale",
          cropVsFF: "Facteur de crop (vs. plein format)",
          notAvailable: "Non disponible",
          diagramTitle: "Diagramme FOV",
          panel2D: "2D",
          panel3D: "3D",
        },
        threeD: {
          view3D: "Vue 3D :",
          projectionIsometric: "Isométrique",
          projectionPerspective: "Perspective",
          zoom: "Zoom",
          reset: "Réinitialiser",
          selectSensorFocalToSee3D:
            "Sélectionne capteur & focale pour voir la vue 3D.",
          sensorPosition: "Position capteur",
          legendFocus: "Mise au point",
          legendNear: "Limite proche",
          legendFar: "Limite lointaine",
          labelHFOV: "HFOV",
          labelVFOV: "VFOV",
          labelSensor: "Capteur",
        },
      },
    },
  },

  es: {
    nav: {
      dashboard: "Panel",
      shots: "Lista de planos",
      settings: "Configuración",
      camera: "Presets de cámara",
      notes: "Notas",
      tools: "Herramientas",
      sensorPreview: "Vista de sensor",
      sensorDb: "Sensor DB",
      fovCalculator: "Calculadora FOV",
      lensMapper: "Lens Mapper",
      flickerControll: "Control de Flicker",
      lightingTools: "Herramientas de iluminación",
      lensEditor: "Editor de lentes",
      cameraSensorEditor: "Editor de cámara/sensor",
    },
    settings: {
      title: "Configuración",
      appearance: "Apariencia",
      language: "Idioma",
      languageOptions: {
        de: "Alemán",
        en: "Inglés",
        fr: "Francés",
        es: "Español",
      },
      offline: "Disponibilidad sin conexión",
    },
    common: {
      loading: "Cargando...",
      save: "Guardar",
      cancel: "Cancelar",
      back: "Atrás",
      yes: "Sí",
      no: "No",
      and: "y",
      notAvailable: "No especificado",
      manual: "Manual",
      auto: "Auto",
      select: "Seleccionar...",
      description: "Descripción",
      notes: "Notas",
      of: "de",
      on: "Activado",
      off: "Desactivado",
      expand: "Expandir",
      collapse: "Colapsar",
      undo: "Deshacer",
      redo: "Rehacer",
    },
    action: {
      view: "Ver",
      edit: "Editar",
      delete: "Eliminar",
      create: "Crear",
      add: "Añadir",
      shotDetails: "Detalles del plano",
      open: "Abrir",
      addSetup: "Añadir setup",
      exportProjectPDF: "Exportar proyecto a PDF",
      newShot: "Nueva toma",
    },
    shot: {
      listTitle: "Lista de planos",
      setupCount: "Configuraciones de cámara",
      detailsTitle: "Información del plano",
      singular: "Toma",
      plural: "Tomas",
      notes: "Notas",
      newNote: "Nueva nota",
      emptyTitle: "No se encontraron tomas",
      emptyMessage: "Ajusta la búsqueda o crea una nueva toma.",
    },
    notes: {
      titleLabel: "Título",
      contentLabel: "Contenido",
      tagsLabel: "Etiquetas (separadas por comas):",
      filterByTags: "Filtrar por etiquetas:",
      addNote: "Añadir nota",
      titlePlaceholder: "Título de la nota",
      contentPlaceholder: "Contenido de la nota",
      tagsPlaceholder: "p. ej., Reunión, Greenscreen, SH_001",
      canvas: {
        createSketch: "Crear boceto",
        tool: "Herramienta",
        toolOptions: {
          pen: "Lápiz",
          rect: "Rectángulo",
          arrow: "Flecha",
          text: "Texto",
        },
        text: "Texto",
        textPlaceholder: "Introducir texto",
        textPrompt: "Introducir texto",
        color: "Color",
        brush: "Pincel",
        loadBackground: "Cargar fondo",
        clear: "Limpiar",
        savePng: "Guardar PNG",
        exportJson: "Exportar JSON",
        importJson: "Importar JSON",
        applyToNote: "Aplicar a la nota",
        filePrefix: "boceto",
        jsonImportError: "Error al importar JSON:",
      },
    },
    search: {
      shotsPlaceholder: "Buscar por nombre de toma o descripción...",
      notesPlaceholder: "Buscar en notas...",
    },
    status: {
      all: "Todos",
      completed: "Completado",
      inProgress: "En progreso",
      pending: "Pendiente",
    },
    section: {
      cameraSetup: "Configuración de cámara",
      cameraSettings: "Ajustes de cámara",
      lensSettings: "Ajustes de lente",
      cameraMovement: "Movimiento de cámara",
      vfxTasks: "Tareas VFX",
      references: "Referencias",
      setupLabel: "Setup",
    },
    camera: {
      manufacturer: "Fabricante",
      model: "Cámara",
      sensor: "Sensor",
      iso: "ISO",
      framerate: "Frecuencia de fotogramas",
      shutter: "Velocidad de obturación",
      shutterAngle: "Ángulo de obturación",
      wb: "Balance de blancos",
      format: "Formato",
      codec: "Códec",
      colorSpace: "Espacio de color",
      lut: "Viewer LUT",
      imageStabilization: "Estabilización de imagen",
      ndFilter: "Filtro ND interno",
      selectManufacturer: "Seleccionar fabricante...",
      selectModel: "Seleccionar modelo...",
      selectCodec: "Seleccionar códec...",
      selectColorSpace: "Seleccionar espacio de color...",
      selectLut: "Seleccionar Viewer LUT...",
      selectFormat: "Seleccionar formato...",
      manualISOPlaceholder: "Ingrese ISO personalizado, p. ej., 850",
      manualWBPlaceholder: "p. ej., 4200K o ingresar valor Kelvin",
      wbOptions: {
        daylight5600: "Luz de día (5600K)",
        tungsten3200: "Tungsteno (3200K)",
        fluorescent: "Fluorescente",
        cloudy: "Nublado",
        shade: "Sombra",
      },
      imageStabilizationOptions: {
        off: "Desactivado",
        standard: "Estándar",
        active: "Activo",
        boost: "Boost",
      },
      ndFilterOptions: {
        none: "Ninguno",
        nd03_1Stop: "ND 0.3 (1 paso)",
        nd06_2Stops: "ND 0.6 (2 pasos)",
        nd09_3Stops: "ND 0.9 (3 pasos)",
        nd12_4Stops: "ND 1.2 (4 pasos)",
        nd15_5Stops: "ND 1.5 (5 pasos)",
        nd18_6Stops: "ND 1.8 (6 pasos)",
      },
    },
    lens: {
      manufacturer: "Fabricante del objetivo",
      lens: "Objetivo",
      focalLength: "Longitud focal",
      aperture: "Apertura",
      focus: "Enfoque",
      focusDistance: "Distancia de enfoque",
      hyperfocalDistance: "Distancia hiperfocal",
      lensStabilization: "Estabilización del objetivo",
      range: "Rango",
      enterValueBetween: "Ingrese un valor entre",
      filter: "Filtro",
      addFilter: "Añadir filtro",
      anamorphic: "Lente anamórfica",
      selectManufacturer: "Seleccionar fabricante...",
      focalLengthZoom: "Longitud focal (zoom)",
      hyperfocalPlaceholder: "p. ej., 5,2 m",
      aperturePlaceholder: "p. ej., f/2.8",
      focusDistancePlaceholder: "p. ej., 3 m",
    },
    movement: {
      movement: "Movimiento",
      type: "Tipo de movimiento",
      direction: "Dirección",
      path: "Trayectoria",
      speed: "Velocidad",
      cameraHeight: "Altura de la cámara",
      dollySetup: "Configuración de dolly",
      trackType: "Tipo de riel (Dolly)",
      trackTypeStraight: "Recto",
      trackTypeCurve: "Curva",
      trackLength: "Longitud del riel",
      head: "Cabezal",
      headFluid: "Fluido",
      headGearhead: "Gearhead",
      mount: "Montaje",
      sliderLength: "Longitud del slider",
      sliderOrientation: "Orientación del slider",
      orientationHorizontal: "Horizontal",
      orientationVertical: "Vertical",
      orientationDiagonal: "Diagonal",
      directionOptions: {
        forward: "Adelante",
        backward: "Atrás",
        sideways: "Lateral",
        circle: "Circular",
        up: "Arriba",
        down: "Abajo",
        diagonal: "Diagonal",
      },
      typeOptions: {
        dolly: "Dolly",
        slider: "Slider",
        craneJib: "Grúa/Jib",
        gimbal: "Gimbal",
        steadicam: "Steadicam",
        handheld: "A mano",
        tripodStatic: "Trípode (estático)",
      },
      jibArmLength: "Longitud del brazo de grúa/jib",
      mountCraneJib: "Montaje (grúa/jib)",
      panDegrees: "Panorámica (°)",
      tiltDegrees: "Inclinación (°)",
      armLengthPlaceholder: "p. ej., 3 m",
      speedPlaceholder: "p. ej., lento o 0,8 m/s",
      cameraHeightPlaceholder: "p. ej., 1,60 m",
      trackLengthPlaceholder: "p. ej., 10 m",
      sliderLengthPlaceholder: "p. ej., 1,0 m",
      mountingPlaceholder: "p. ej., Dolly, Trípode, Placa base",
      mountPlaceholder: "p. ej., Low-Mode, Hi-Hat",
      panPlaceholder: "p. ej., 30°",
      tiltPlaceholder: "p. ej., 10°",
      notesPlaceholder: "Notas adicionales de movimiento/configuración",
    },
    vfx: {
      supervisor: "Supervisor VFX",
      tasks: "Tareas",
      plates: "Plates",
      checklist: {
        cleanplates: "Cleanplates filmadas",
        hdris: "HDRIs capturadas",
        setReferences: "Referencias del set fotografiadas",
        chromeBall: "Bola cromada usada",
        grayBall: "Bola gris usada",
        colorChecker: "ColorChecker usado",
        distortionGrids: "Cuadrículas de distorsión filmadas",
        measurementsTaken: "Mediciones tomadas",
        threeDScans: "Escaneos 3D realizados",
      },
      distortionNotesPlaceholder: "Notas adicionales",
      measurementsNotesPlaceholder: "Indicaciones adicionales de medición",
      threeDScansNotesPlaceholder: "Detalles de escaneo, calibración, etc.",
    },
    dashboard: {
      title: "Panel",
      myProjects: "Mis proyectos",
      viewShots: "Ver planos",
      newProject: "Crear nuevo proyecto",
      plannedShotsCount: "Número de planos previstos",
      production: "Producción",
      director: "Director",
      cinematographer: "Director de fotografía",
      vfxSupervisor: "Supervisor VFX",
      created: "Creado",
      progress: "Progreso",
      projectName: "Nombre del proyecto",
      projectNamePlaceholder: "Ingrese el nombre del proyecto",
      productionPlaceholder: "Nombre de la compañía de producción",
      directorPlaceholder: "Nombre del director",
      cinematographerPlaceholder: "Nombre del director de fotografía",
      vfxSupervisorPlaceholder: "Nombre del supervisor VFX",
      createProject: "Crear proyecto",
      projectDetails: "Detalles del proyecto",
      emptyTitle: "Aún no hay proyectos",
      emptyMessage: "Crea tu primer proyecto para comenzar.",
    },
    tools: {
      flicker: {
        title: "Control de Flicker",
        cameraInfo: "Info de cámara",
        mainsFrequency: "Frecuencia de red",
        framerate: "Frecuencia de cuadros",
        flickerSafe: "Sin parpadeo",
        shutterAngle: "Obturador",
        exposureTime: "Tiempo de exposición",
        na: "N/A",
        manufacturer: "Fabricante de cámara",
        arriLogC3: "ARRI LogC3",
        arriLogC4: "ARRI LogC4",
        eiBehavior: "Comportamiento EI",
        shutterCalcTitle: "Calculadora de ángulo de obturador",
        framerateFpsLabel: "Frecuencia (fps)",
        shutterAngleLabel: "Ángulo de obturador (°)",
        exposureTimeLabel: "Tiempo de exposición",
        apply180Rule: "Aplicar regla de 180°",
        formulaLabel: "Fórmula: t = (Ángulo/360) · (1/FPS)",
      },
      fov: {
        header: "Calculadora FOV",
        description: "Calcular campo de visión por formato y focal.",
        infoTitle: "Info",
        legendColorsTitle: "Colores del diagrama",
        legendBlue: "Azul: VFOV; punto azul = centro óptico.",
        legendRed: "Rojo: HFOV – rayos extremos izquierda/derecha.",
        legendGray:
          "Gris: marco del sensor (derecha) en mm, diagonal discontinua (DFOV).",
        readTitle: "Qué puedes leer",
        readHFOV: "HFOV/VFOV/DFOV: ángulos en vivo.",
        readSensor: "Tamaño del sensor: ancho × alto en mm.",
        readCrop: "Factor de recorte: diagonal vs. full frame.",
        hintTitle: "Nota",
        hintText: "Vista esquemática: ángulos y escala, no distorsión real.",
        controls: {
          manufacturer: "Fabricante",
          camera: "Cámara",
          format: "Formato",
          selectPrompt: "Seleccione…",
          lensManufacturer: "Fabricante del objetivo",
          lens: "Objetivo",
          anamorph: "Anamórfico",
          focalLengthMm: "Longitud focal (mm)",
          projection: "Proyección",
          projectionOptions: {
            rectilinear: "Rectilíneo",
            fisheyeEquidistant: "Ojo de pez (equidistante)",
            fisheyeStereographic: "Ojo de pez (estereográfico)",
          },
          apertureFN: "Apertura (f/N)",
          focusDistanceM: "Distancia de enfoque (m)",
          focusDistance: "Distancia de enfoque",
          resultTitle: "Resultado",
          sensorSize: "Tamaño del sensor",
          lensInfo: "Objetivo",
          lensType: "Tipo de objetivo",
          anamorphFactor: "Factor anamórfico",
          horizontal: "Horizontal",
          vertical: "Vertical",
          diagonal: "Diagonal",
          cropVsFF: "Factor de recorte (vs. full frame)",
          notAvailable: "No disponible",
          diagramTitle: "Diagrama FOV",
          panel2D: "2D",
          panel3D: "3D",
        },
        threeD: {
          view3D: "Vista 3D:",
          projectionIsometric: "Isométrica",
          projectionPerspective: "Perspectiva",
          zoom: "Zoom",
          reset: "Reiniciar",
          selectSensorFocalToSee3D:
            "Selecciona sensor y focal para ver la vista 3D.",
          sensorPosition: "Posición del sensor",
          legendFocus: "Enfoque",
          legendNear: "Límite cercano",
          legendFar: "Límite lejano",
          labelHFOV: "HFOV",
          labelVFOV: "VFOV",
          labelSensor: "Sensor",
        },
      },
    },
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    try {
      const stored = localStorage.getItem("app_language");
      return stored || "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem("app_language", language);
    } catch {}
  }, [language]);

  const t = useMemo(() => {
    const dict = translations[language] || translations.en;
    return (key, fallback) => {
      if (!key) return fallback ?? "";
      const parts = key.split(".");
      let current = dict;
      for (const p of parts) {
        if (current && Object.prototype.hasOwnProperty.call(current, p)) {
          current = current[p];
        } else {
          current = undefined;
          break;
        }
      }
      if (typeof current === "string") return current;
      return fallback ?? key;
    };
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language]);
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;