name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Verify build output and env
        run: |
          echo "VITE_API_URL=$VITE_API_URL"
          echo "Listing project root:"
          ls -la
          echo "Listing dist:"
          if [ ! -d "dist" ]; then
            echo "dist directory missing after build";
            exit 1;
          fi
          ls -la dist | head -n 200
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Preflight Cloudflare config
        run: |
          echo "::group::Cloudflare Config"
          echo "PROJECT_NAME=$PROJECT_NAME"
          if [ "$HAS_CF_TOKEN" != "true" ]; then echo "CLOUDFLARE_API_TOKEN missing"; exit 1; fi
          if [ "$HAS_ACCOUNT_ID" != "true" ]; then echo "CLOUDFLARE_ACCOUNT_ID missing"; exit 1; fi
          echo "::endgroup::"
        env:
          PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME || 'vfx-supervision' }}
          HAS_CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
          HAS_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID != '' }}

      - name: Cloudflare API auth smoke test
        run: |
          set -e
          echo "::group::Verify API token"
          VERIFY=$(curl -sS -H "Authorization: Bearer $CF_TOKEN" https://api.cloudflare.com/client/v4/user/tokens/verify)
          echo "$VERIFY"
          echo "$VERIFY" | grep -q '"success":true' || { echo "Token verification failed. Ensure token is valid and not expired."; exit 1; }
          echo "::endgroup::"

          echo "::group::Check Pages access"
          PAGES=$(curl -sS -H "Authorization: Bearer $CF_TOKEN" "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects?per_page=1")
          echo "$PAGES"
          echo "$PAGES" | grep -q '"success":true' || { echo "Pages API not accessible for this token/account. Ensure permission 'Cloudflare Pages: Edit' and correct Account ID."; exit 1; }
          echo "::endgroup::"
        env:
          CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Node/npm info
        run: |
          node -v
          npm -v
          npx --version

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME || 'vfx-supervision' }}
          directory: ./dist
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}