name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Verify build output and env
        run: |
          echo "VITE_API_URL=$VITE_API_URL"
          echo "Listing project root:"
          ls -la
          echo "Listing dist:"
          if [ ! -d "dist" ]; then
            echo "dist directory missing after build";
            exit 1;
          fi
          ls -la dist | head -n 200
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Preflight Cloudflare config
        run: |
          echo "::group::Cloudflare Config"
          echo "PROJECT_NAME=$PROJECT_NAME"
          if [ "$HAS_CF_TOKEN" != "true" ]; then echo "CLOUDFLARE_API_TOKEN missing"; exit 1; fi
          if [ "$HAS_ACCOUNT_ID" != "true" ]; then echo "CLOUDFLARE_ACCOUNT_ID missing"; exit 1; fi
          echo "::endgroup::"
        env:
          PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME || 'vfx-supervision' }}
          HAS_CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
          HAS_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID != '' }}

      - name: Cloudflare API auth smoke test
        run: |
          set -euo pipefail

          # Sanitize token (remove CR/LF and spaces) to avoid invalid header format
          TOKEN_TRIMMED=$(printf "%s" "$CF_TOKEN" | tr -d '\r\n ')
          if [ -z "$TOKEN_TRIMMED" ]; then
            echo "CLOUDFLARE_API_TOKEN is empty after trimming. Secret likely not set or contains only whitespace.";
            exit 1;
          fi

          echo "::group::Verify API token"
          VERIFY=$(curl -sS --retry 2 --retry-delay 1 \
            -H "Authorization: Bearer $TOKEN_TRIMMED" \
            https://api.cloudflare.com/client/v4/user/tokens/verify)
          echo "$VERIFY"
          if echo "$VERIFY" | grep -q '"success":true'; then
            echo "::endgroup::"
          else
            if echo "$VERIFY" | grep -q '"code":6111'; then
              echo "Authorization header format invalid. Ensure the secret is an API Token only (no quotes, no spaces, no newlines).";
              echo "Also ensure you're using an API Token, not the Global API Key.";
            fi
            exit 1;
          fi

          echo "::group::Check Pages access"
          PAGES=$(curl -sS --retry 2 --retry-delay 1 \
            -H "Authorization: Bearer $TOKEN_TRIMMED" \
            "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects?per_page=1")
          echo "$PAGES"
          echo "$PAGES" | grep -q '"success":true' || { echo "Pages API not accessible for this token/account. Ensure permission 'Cloudflare Pages: Edit' and correct Account ID."; exit 1; }
          echo "::endgroup::"
        env:
          CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Node/npm info
        run: |
          node -v
          npm -v
          npx --version

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME || 'vfx-supervision' }}
          directory: ./dist
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}